services:
  geoservice: &app
    container_name: geoservice
    image: ${GCP_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_ARTIFACT_REGISTRY_NAME}/${GCP_IMAGE_NAME}:${GCP_IMAGE_TAG}
    restart: always
    stop_signal: SIGTERM
    stop_grace_period: 30s
    env_file:
      - .env.gcp
    networks:
      - geoservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"

networks:
  geoservice:
    driver: bridge
